/* eslint-disable */
import { FuseNavigationItem } from '@fuse/components/navigation'

export const defaultNavigation: FuseNavigationItem[] = [
  {
    id: 'admin-management',
    title: 'Admin Management',
    permissions: ['super', 'admin-permission-read', 'admin-role-read', 'admin-user-read'],
    type: 'group',
    icon: 'heroicons_outline:cog-6-tooth',
    children: [
      {
        id: 'admin-permission',
        title: 'Ruxsatlar',
        permissions: ['super', 'admin-permission-read'],
        type: 'basic',
        icon: 'heroicons_outline:key',
        link: '/admin-permission',
      },
      {
        id: 'admin-role',
        title: 'Rollar',
        permissions: ['super', 'admin-role-read'],
        type: 'basic',
        icon: 'heroicons_outline:shield-check',
        link: '/admin-role',
      },
      {
        id: 'admin-user',
        title: 'Adminlar',
        permissions: ['super', 'admin-user-read'],
        type: 'basic',
        icon: 'heroicons_outline:users',
        link: '/admin-user',
      },
    ],
  },
  {
    id: 'course-management',
    title: 'Kurs boshqaruvi',
    permissions: [
      'super',
      'sp-category-read',
      'sp-level-read',
      'sp-courses-read',
      'sp-materials-read',
      'sp-tests-read',
    ],
    type: 'group',
    icon: 'heroicons_outline:academic-cap',
    children: [
      {
        id: 'sp-category',
        title: 'Kategoriyalar',
        permissions: ['super', 'sp-category-read'],
        type: 'basic',
        icon: 'heroicons_outline:squares-2x2',
        link: '/sp-category',
      },
      {
        id: 'sp-level',
        title: 'Darajalar',
        permissions: ['super', 'sp-level-read'],
        type: 'basic',
        icon: 'heroicons_outline:signal',
        link: '/sp-level',
      },
      {
        id: 'sp-courses',
        title: 'Kurslar',
        permissions: ['super', 'sp-courses-read'],
        type: 'basic',
        icon: 'heroicons_outline:play-circle',
        link: '/sp-courses',
      },
      {
        id: 'sp-materials',
        title: 'Materiallar',
        permissions: ['super', 'sp-materials-read'],
        type: 'basic',
        icon: 'heroicons_outline:document-text',
        link: '/sp-materials',
      },
      {
        id: 'sp-tests',
        title: 'Testlar',
        permissions: ['super', 'sp-tests-read'],
        type: 'basic',
        icon: 'heroicons_outline:clipboard-document-check',
        link: '/sp-tests',
      },
    ],
  },
  {
    id: 'system-settings',
    title: 'Tizim sozlamalari',
    permissions: ['super', 'translation-read'],
    type: 'group',
    icon: 'heroicons_outline:cog-8-tooth',
    children: [
      {
        id: 'translation',
        title: 'Tarjimalar',
        permissions: ['super', 'translation-read'],
        type: 'basic',
        icon: 'heroicons_outline:language',
        link: '/translation',
      },
    ],
  },
]
