import { Inject, Injectable } from '@angular/core'
import { FileType } from 'app/shared/enums/file_type'

@Injectable()
export class Constants {
  public static readonly FILE_MAX_SIZE = {
    [FileType.image]: 4 * 1024 * 1024,
    [FileType.video]: 40 * 1024 * 1024,
    [FileType.pdf]: 15 * 1024 * 1024,
    [FileType.word]: 15 * 1024 * 1024,
  }

  public static readonly FILE_ALLOWED_MIMES = {
    [FileType.image]: ['image/jpeg', 'image/png', 'image/gif'],
    [FileType.video]: ['video/mp4'],
    [FileType.pdf]: ['application/pdf'],
    [FileType.word]: [
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ],
  }

  public static readonly PRIME_ICONS = [
    'pi pi-home',
    'pi pi-star',
    'pi pi-heart',
    'pi pi-user',
    'pi pi-users',
    'pi pi-cog',
    'pi pi-bell',
    'pi pi-envelope',
    'pi pi-calendar',
    'pi pi-clock',
    'pi pi-map-marker',
    'pi pi-phone',
    'pi pi-mobile',
    'pi pi-laptop',
    'pi pi-desktop',
    'pi pi-tablet',
    'pi pi-camera',
    'pi pi-video',
    'pi pi-image',
    'pi pi-file',
    'pi pi-folder',
    'pi pi-folder-open',
    'pi pi-download',
    'pi pi-upload',
    'pi pi-cloud',
    'pi pi-database',
    'pi pi-server',
    'pi pi-wifi',
    'pi pi-globe',
    'pi pi-link',
    'pi pi-bookmark',
    'pi pi-tag',
    'pi pi-tags',
    'pi pi-search',
    'pi pi-filter',
    'pi pi-sort',
    'pi pi-list',
    'pi pi-th-large',
    'pi pi-table',
    'pi pi-chart-bar',
    'pi pi-chart-line',
    'pi pi-chart-pie',
    'pi pi-calculator',
    'pi pi-money-bill',
    'pi pi-credit-card',
    'pi pi-shopping-cart',
    'pi pi-shopping-bag',
    'pi pi-gift',
    'pi pi-trophy',
    'pi pi-medal',
    'pi pi-flag',
    'pi pi-bookmark',
    'pi pi-thumbs-up',
    'pi pi-thumbs-down',
    'pi pi-like',
    'pi pi-share',
    'pi pi-comment',
    'pi pi-eye',
    'pi pi-eye-slash',
    'pi pi-lock',
    'pi pi-unlock',
    'pi pi-key',
    'pi pi-shield',
    'pi pi-check',
    'pi pi-times',
    'pi pi-plus',
    'pi pi-minus',
    'pi pi-pencil',
    'pi pi-trash',
    'pi pi-copy',
    'pi pi-paste',
    'pi pi-cut',
    'pi pi-save',
    'pi pi-print',
    'pi pi-refresh',
    'pi pi-sync',
    'pi pi-undo',
    'pi pi-redo',
    'pi pi-forward',
    'pi pi-backward',
    'pi pi-play',
    'pi pi-pause',
    'pi pi-stop',
    'pi pi-volume-up',
    'pi pi-volume-down',
    'pi pi-volume-off',
    'pi pi-microphone',
    'pi pi-headphones',
    'pi pi-music',
    'pi pi-book',
    'pi pi-graduation-cap',
    'pi pi-university',
    'pi pi-building',
    'pi pi-hospital',
    'pi pi-car',
    'pi pi-plane',
    'pi pi-train',
    'pi pi-ship',
    'pi pi-bicycle',
    'pi pi-motorcycle',
    'pi pi-bus',
    'pi pi-taxi',
    'pi pi-truck',
    'pi pi-gas-pump',
    'pi pi-road',
    'pi pi-map',
    'pi pi-compass',
    'pi pi-location-arrow',
    'pi pi-sun',
    'pi pi-moon',
    'pi pi-cloud',
    'pi pi-umbrella',
    'pi pi-snowflake',
    'pi pi-fire',
    'pi pi-bolt',
    'pi pi-leaf',
    'pi pi-tree',
    'pi pi-flower',
    'pi pi-apple',
    'pi pi-coffee',
    'pi pi-glass',
    'pi pi-beer',
    'pi pi-pizza',
    'pi pi-hamburger',
    'pi pi-cutlery',
    'pi pi-birthday-cake',
    'pi pi-gamepad',
    'pi pi-puzzle-piece',
    'pi pi-dice',
    'pi pi-chess',
    'pi pi-football',
    'pi pi-basketball',
    'pi pi-baseball',
    'pi pi-tennis',
    'pi pi-golf',
    'pi pi-swimming',
    'pi pi-running',
    'pi pi-walking',
    'pi pi-cycling',
    'pi pi-dumbbell',
    'pi pi-weight',
    'pi pi-heartbeat',
    'pi pi-stethoscope',
    'pi pi-pills',
    'pi pi-syringe',
    'pi pi-bandage',
    'pi pi-first-aid',
    'pi pi-ambulance',
    'pi pi-wheelchair',
    'pi pi-baby',
    'pi pi-child',
    'pi pi-female',
    'pi pi-male',
    'pi pi-elderly',
    'pi pi-family',
    'pi pi-couple',
    'pi pi-friends',
    'pi pi-team',
    'pi pi-group',
    'pi pi-community',
    'pi pi-network',
    'pi pi-organization',
    'pi pi-company',
    'pi pi-factory',
    'pi pi-warehouse',
    'pi pi-store',
    'pi pi-shop',
    'pi pi-market',
    'pi pi-bank',
    'pi pi-atm',
    'pi pi-wallet',
    'pi pi-coins',
    'pi pi-dollar',
    'pi pi-euro',
    'pi pi-pound',
    'pi pi-yen',
    'pi pi-ruble',
    'pi pi-bitcoin',
    'pi pi-ethereum',
    'pi pi-paypal',
    'pi pi-stripe',
    'pi pi-visa',
    'pi pi-mastercard',
    'pi pi-american-express',
  ]
}
